[package]
name = "example"
version = "0.1.0"
authors = ["Bram Vandenbogaerde <bram.vandenbogaerde@gmail.com>"]

[dependencies]
rocket = "0.3.0"
rocket-simpleauth = {path = "../"}
rocket_codegen = "0.3.0"
