[package]
name = "dummy_auth"
version = "0.1.0"
authors = ["Daniel Wiesenberg <weasy@hotmail.de>","Bram Vandenbogaerde <bram.vandenbogaerde@gmail.com>"]
publish = false

[dependencies]
rocket = "0.4.0"
rocket_auth = {path = "../"}
rocket_codegen = "0.4.0"
