[package]
name = "dummy_auth"
version = "0.1.0"
authors = ["Bram Vandenbogaerde <bram.vandenbogaerde@gmail.com>"]
publish = false

[dependencies]
rocket = "0.4.0"
rocket-simpleauth = {path = "../"}
rocket_codegen = "0.4.0"
